version: '3'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - api_network

  api_server:
    build: .
    container_name: php-api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - 9000:80
    depends_on:
      - db
    volumes:
      - ./api:/var/www/html
    networks:
      - api_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
    depends_on:
      - db
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  mariadb_data: